/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.form;

import com.dbcon.HyperMethod;
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author cyber
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanelMain = new javax.swing.JPanel();
        jPanelClose = new javax.swing.JPanel();
        jLabelClose = new javax.swing.JLabel();
        jPanelMinimize = new javax.swing.JPanel();
        jLabelMinimize = new javax.swing.JLabel();
        jPanelCenter = new javax.swing.JPanel();
        jPanelLeft = new javax.swing.JPanel();
        jLabelImage = new javax.swing.JLabel();
        jPanelHeader = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanelRight = new javax.swing.JPanel();
        jPanelInfos = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldUsername = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPasswordFieldPass = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldEMail = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldPhone = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaAddress = new javax.swing.JTextArea();
        jButtonRegister = new javax.swing.JButton();
        jButtonClearAll = new javax.swing.JButton();
        jToggleButtonLogin = new javax.swing.JToggleButton();

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registration Page");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanelMain.setBackground(new java.awt.Color(0, 204, 204));
        jPanelMain.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 102, 102)));
        jPanelMain.setPreferredSize(new java.awt.Dimension(1200, 900));

        jPanelClose.setBackground(new java.awt.Color(0, 204, 204));
        jPanelClose.setPreferredSize(new java.awt.Dimension(45, 65));
        jPanelClose.setLayout(new java.awt.BorderLayout());

        jLabelClose.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabelClose.setForeground(new java.awt.Color(204, 204, 204));
        jLabelClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelClose.setText("X");
        jLabelClose.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseExited(evt);
            }
        });
        jPanelClose.add(jLabelClose, java.awt.BorderLayout.CENTER);

        jPanelMinimize.setBackground(new java.awt.Color(0, 204, 204));
        jPanelMinimize.setPreferredSize(new java.awt.Dimension(45, 65));
        jPanelMinimize.setLayout(new java.awt.BorderLayout());

        jLabelMinimize.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabelMinimize.setForeground(new java.awt.Color(204, 204, 204));
        jLabelMinimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMinimize.setText("-");
        jLabelMinimize.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelMinimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelMinimizeMouseExited(evt);
            }
        });
        jPanelMinimize.add(jLabelMinimize, java.awt.BorderLayout.CENTER);

        jPanelCenter.setLayout(new java.awt.GridLayout(1, 2));

        jPanelLeft.setBackground(new java.awt.Color(0, 204, 204));
        jPanelLeft.setLayout(new java.awt.BorderLayout());

        jLabelImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/output-onlinepngtools.png"))); // NOI18N
        jPanelLeft.add(jLabelImage, java.awt.BorderLayout.CENTER);

        jPanelHeader.setBackground(new java.awt.Color(0, 204, 204));
        jPanelHeader.setLayout(new java.awt.GridLayout(3, 0, 0, 16));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 204, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Registration Page");
        jPanelHeader.add(jLabel2);

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 204, 51));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Please Fill Out The Form");
        jPanelHeader.add(jLabel3);

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 204, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("To Complete Your Registration");
        jPanelHeader.add(jLabel4);

        jPanelLeft.add(jPanelHeader, java.awt.BorderLayout.NORTH);

        jPanelCenter.add(jPanelLeft);

        jPanelRight.setBackground(new java.awt.Color(51, 255, 255));
        jPanelRight.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(0, 204, 204), new java.awt.Color(51, 255, 255)));

        jPanelInfos.setBackground(new java.awt.Color(51, 255, 255));
        jPanelInfos.setPreferredSize(new java.awt.Dimension(450, 650));
        jPanelInfos.setLayout(new java.awt.GridLayout(0, 2, 10, 30));

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 153, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/account-64x64-1214443.png"))); // NOI18N
        jLabel5.setText("Username: ");
        jPanelInfos.add(jLabel5);

        jTextFieldUsername.setBackground(new java.awt.Color(204, 255, 255));
        jTextFieldUsername.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jTextFieldUsername.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldUsernameKeyTyped(evt);
            }
        });
        jPanelInfos.add(jTextFieldUsername);

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 153, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lock-64x64-1213982.png"))); // NOI18N
        jLabel6.setText(" Password: ");
        jPanelInfos.add(jLabel6);

        jPasswordFieldPass.setBackground(new java.awt.Color(204, 255, 255));
        jPasswordFieldPass.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jPasswordFieldPass.setForeground(new java.awt.Color(0, 0, 0));
        jPasswordFieldPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPasswordFieldPassKeyTyped(evt);
            }
        });
        jPanelInfos.add(jPasswordFieldPass);

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 153, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/message-64x64-1214402.png"))); // NOI18N
        jLabel7.setText("      E-Mail: ");
        jPanelInfos.add(jLabel7);

        jTextFieldEMail.setBackground(new java.awt.Color(204, 255, 255));
        jTextFieldEMail.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jTextFieldEMail.setForeground(new java.awt.Color(0, 0, 0));
        jPanelInfos.add(jTextFieldEMail);

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 153, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/call-64x64-1214404.png"))); // NOI18N
        jLabel8.setText("     Phone: ");
        jPanelInfos.add(jLabel8);

        jTextFieldPhone.setBackground(new java.awt.Color(204, 255, 255));
        jTextFieldPhone.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jTextFieldPhone.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldPhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldPhoneKeyTyped(evt);
            }
        });
        jPanelInfos.add(jTextFieldPhone);

        jLabel9.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 153, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\cyber\\Documents\\Java Development Resources\\IconPack\\location-and-map\\png-64\\location-64x64-1214139.png")); // NOI18N
        jLabel9.setText("  Address: ");
        jLabel9.setToolTipText("");
        jPanelInfos.add(jLabel9);

        jTextAreaAddress.setBackground(new java.awt.Color(204, 255, 255));
        jTextAreaAddress.setColumns(20);
        jTextAreaAddress.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jTextAreaAddress.setForeground(new java.awt.Color(0, 0, 0));
        jTextAreaAddress.setRows(5);
        jTextAreaAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextAreaAddressKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(jTextAreaAddress);

        jPanelInfos.add(jScrollPane1);

        jButtonRegister.setBackground(new java.awt.Color(204, 255, 255));
        jButtonRegister.setFont(new java.awt.Font("Verdana", 1, 22)); // NOI18N
        jButtonRegister.setForeground(new java.awt.Color(0, 0, 0));
        jButtonRegister.setText("REGISTER");
        jButtonRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegisterActionPerformed(evt);
            }
        });
        jPanelInfos.add(jButtonRegister);

        jButtonClearAll.setBackground(new java.awt.Color(204, 255, 255));
        jButtonClearAll.setFont(new java.awt.Font("Verdana", 1, 22)); // NOI18N
        jButtonClearAll.setForeground(new java.awt.Color(0, 0, 0));
        jButtonClearAll.setText("CLEAR ALL");
        jButtonClearAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearAllActionPerformed(evt);
            }
        });
        jPanelInfos.add(jButtonClearAll);

        jToggleButtonLogin.setBackground(new java.awt.Color(204, 255, 255));
        jToggleButtonLogin.setFont(new java.awt.Font("Verdana", 1, 22)); // NOI18N
        jToggleButtonLogin.setForeground(new java.awt.Color(0, 0, 0));
        jToggleButtonLogin.setText("LOGIN");
        jToggleButtonLogin.setPreferredSize(new java.awt.Dimension(160, 60));
        jToggleButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelRightLayout = new javax.swing.GroupLayout(jPanelRight);
        jPanelRight.setLayout(jPanelRightLayout);
        jPanelRightLayout.setHorizontalGroup(
            jPanelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRightLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jPanelInfos, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRightLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jToggleButtonLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(209, 209, 209))
        );
        jPanelRightLayout.setVerticalGroup(
            jPanelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRightLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jPanelInfos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jToggleButtonLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelCenter.add(jPanelRight);

        javax.swing.GroupLayout jPanelMainLayout = new javax.swing.GroupLayout(jPanelMain);
        jPanelMain.setLayout(jPanelMainLayout);
        jPanelMainLayout.setHorizontalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelCenter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelMainLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanelMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanelClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanelMainLayout.setVerticalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelCenter, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseEntered
        jPanelClose.setBackground(Color.red);
        jLabelClose.setForeground(Color.white);
    }//GEN-LAST:event_jLabelCloseMouseEntered

    private void jLabelCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseExited
        jPanelClose.setBackground(new Color(0, 204, 204));
        jLabelClose.setForeground(new Color(204, 204, 204));
    }//GEN-LAST:event_jLabelCloseMouseExited

    private void jLabelMinimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinimizeMouseEntered
        jPanelMinimize.setBackground(new Color(102, 255, 255));
        jLabelMinimize.setForeground(Color.white);
    }//GEN-LAST:event_jLabelMinimizeMouseEntered

    private void jLabelMinimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinimizeMouseExited
        jPanelMinimize.setBackground(new Color(0, 204, 204));
        jLabelMinimize.setForeground(new Color(204, 204, 204));
    }//GEN-LAST:event_jLabelMinimizeMouseExited

    private void jLabelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabelCloseMouseClicked

    private void jLabelMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinimizeMouseClicked
        this.setState(java.awt.Frame.ICONIFIED);
    }//GEN-LAST:event_jLabelMinimizeMouseClicked

    private void jButtonClearAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearAllActionPerformed
        this.jTextFieldUsername.setText("");
        this.jPasswordFieldPass.setText("");
        this.jTextFieldEMail.setText("");
        this.jTextFieldPhone.setText("");
        this.jTextAreaAddress.setText("");
    }//GEN-LAST:event_jButtonClearAllActionPerformed

    private void jTextFieldUsernameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldUsernameKeyTyped
        if (!isValidCharForUsername(evt))
            evt.consume();
    }//GEN-LAST:event_jTextFieldUsernameKeyTyped

    private void jPasswordFieldPassKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordFieldPassKeyTyped
        if (jPasswordFieldPass.getPassword().length > 23)
            evt.consume();
    }//GEN-LAST:event_jPasswordFieldPassKeyTyped

    private void jTextFieldPhoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPhoneKeyTyped
        if (!Character.isDigit(evt.getKeyChar()) || (jTextFieldPhone.getText().length() > 10))
            evt.consume();
    }//GEN-LAST:event_jTextFieldPhoneKeyTyped

    private void jTextAreaAddressKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextAreaAddressKeyTyped
        if (!isValidCharacterAddress(evt)) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextAreaAddressKeyTyped

    private void jButtonRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegisterActionPerformed
        if (jTextFieldUsername.getText().length() == 0 || jTextFieldEMail.getText().length() == 0 || jTextFieldPhone.getText().length() == 0
                || jTextAreaAddress.getText().length() == 0 || jPasswordFieldPass.getPassword().length == 0) {
            JOptionPane.showMessageDialog(this, "All these information are neccesary.\n"
                    + "Please fill all of them!", "WARNING", JOptionPane.WARNING_MESSAGE);
        } else if (isValidEmail()) {
            JOptionPane.showMessageDialog(this, "Invalid e-mail address format.\n"
                    + "Please check it!", "WARNING", JOptionPane.WARNING_MESSAGE);
        } else if (isUsernameExists()) {
            JOptionPane.showMessageDialog(this, "Username is in use.\n"
                    + "Please change the username.", "WARNING", JOptionPane.WARNING_MESSAGE);
        } else if (isMailExists()) {
            JOptionPane.showMessageDialog(this, "E-Mail address is in use.\n"
                    + "Please change the E-Mail address.", "WARNING", JOptionPane.WARNING_MESSAGE);
        } else if (isPhoneExists()) {
            JOptionPane.showMessageDialog(this, "Phone number is in use.\n"
                    + "Please change the phone number.", "WARNING", JOptionPane.WARNING_MESSAGE);
        } else {
            String username = jTextFieldUsername.getText();
            String password = String.valueOf(jPasswordFieldPass.getPassword());
            String mail = jTextFieldEMail.getText();
            String phone = jTextFieldPhone.getText();
            String address = jTextAreaAddress.getText();
            try {
                var conn = HyperMethod.getConnection();
                var pst = conn.prepareStatement("insert into users (user_id, user_username, user_password, user_mail, user_phone, user_address, role_id) "
                        + "values (NULL,?,?,?,?,?,100)");
                pst.setString(1, username);
                pst.setString(2, password);
                pst.setString(3, mail);
                pst.setString(4, phone);
                pst.setString(5, address);
                int create_row = pst.executeUpdate();
                if (create_row == 1) {
                    JOptionPane.showMessageDialog(this, "Account has been created successfully.\n"
                            + "Redirecting you to login page.", "SUCCESS", JOptionPane.INFORMATION_MESSAGE);
                    Login login = new Login();
                    login.setVisible(true);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "There has been an error while creating your account.\n"
                            + "Please contact the library manager", "ERROR", JOptionPane.ERROR_MESSAGE);
                }

            } catch (SQLException ex) {
                Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButtonRegisterActionPerformed

    private void jToggleButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonLoginActionPerformed
        var tmp = JOptionPane.showConfirmDialog(this, "Are you sure you want to go back to\n"
                + "the login page without completing\nyour registration?", 
                "Are You Sure?", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (tmp == JOptionPane.YES_OPTION) {
            Login login = new Login();
            login.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jToggleButtonLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClearAll;
    private javax.swing.JButton jButtonRegister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelClose;
    private javax.swing.JLabel jLabelImage;
    private javax.swing.JLabel jLabelMinimize;
    private javax.swing.JPanel jPanelCenter;
    private javax.swing.JPanel jPanelClose;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JPanel jPanelInfos;
    private javax.swing.JPanel jPanelLeft;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JPanel jPanelMinimize;
    private javax.swing.JPanel jPanelRight;
    private javax.swing.JPasswordField jPasswordFieldPass;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaAddress;
    private javax.swing.JTextField jTextFieldEMail;
    private javax.swing.JTextField jTextFieldPhone;
    private javax.swing.JTextField jTextFieldUsername;
    private javax.swing.JToggleButton jToggleButtonLogin;
    // End of variables declaration//GEN-END:variables

    private boolean isValidCharForUsername(java.awt.event.KeyEvent evt) {

        if (!Character.isLetter(evt.getKeyChar()) && !Character.isDigit(evt.getKeyChar()) && !(evt.getKeyChar() == '_')) {
            return false;
        } else if (jTextFieldUsername.getText().length() > 23) {
            return false;
        }
        return true;
    }

    private boolean isValidEmail() {
        final String EMAIL_REGEX = "^[\\w-_\\.+]*[\\w-_\\.]\\@([\\w]+\\.)+[\\w]+[\\w]$";
        if (jTextFieldEMail.getText().matches(EMAIL_REGEX)) {
            return false;
        }
        return true;
    }

    private boolean isValidCharacterAddress(java.awt.event.KeyEvent evt) {
        if (!Character.isLetter(evt.getKeyChar()) && !Character.isDigit(evt.getKeyChar())
                && !(evt.getKeyChar() == '.') && !(evt.getKeyChar() == ':')
                && !(evt.getKeyChar() == '/') && !(evt.getKeyChar() == ' ')) {
            return false;
        }
        return true;
    }

    private boolean isUsernameExists() {
        boolean exists;
        String username;
        try {
            username = jTextFieldUsername.getText();
            var conn = HyperMethod.getConnection();
            var pst = conn.prepareStatement("select user_username from users where user_username = ?");
            pst.setString(1, username);
            var rs = pst.executeQuery();
            exists = rs.next();
            if (exists) {
                rs.close();
                pst.close();
                conn.close();
                return true;
            }
        } catch (SQLException ex) {
            Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
        }
        return false;
    }

    private boolean isMailExists() {
        boolean exists;
        String mail;
        try {
            mail = jTextFieldEMail.getText();
            var conn = HyperMethod.getConnection();
            var pst = conn.prepareStatement("select user_mail from users where user_mail = ?");
            pst.setString(1, mail);
            var rs = pst.executeQuery();
            exists = rs.next();
            if (exists) {
                rs.close();
                pst.close();
                conn.close();
                return true;
            }
        } catch (SQLException ex) {
            Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
        }
        return false;
    }

    private boolean isPhoneExists() {
        boolean exists;
        String phone;
        try {
            phone = jTextFieldPhone.getText();
            var conn = HyperMethod.getConnection();
            var pst = conn.prepareStatement("select user_phone from users where user_phone = ?");
            pst.setString(1, phone);
            var rs = pst.executeQuery();
            exists = rs.next();
            if (exists) {
                rs.close();
                pst.close();
                conn.close();
                return true;
            }
        } catch (SQLException ex) {
            Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
        }
        return false;
    }
}
